services:
  mysql:
    image: mysql:8.4
    container_name: simplified-payment-mysql
    environment:
      MYSQL_DATABASE: payment_db
      MYSQL_USER: payment_user
      MYSQL_PASSWORD: payment_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - simplified-payment-mysql-data:/var/lib/mysql

volumes:
  simplified-payment-mysql-data: